-- Table des logs
CREATE TABLE STG_RAW_LOG (
  ID_LOG     NUMBER PRIMARY KEY,
  TABLE_NAME VARCHAR2(100),
  LOG_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ressources atmosphériques (métadonnées)
CREATE TABLE STG_RAW_ATMO_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500),
  LOG_ID     NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources atmosphériques (taux par planète)
CREATE TABLE STG_RAW_ATMO_RES_RATE (
  RESOURCE_NAME  VARCHAR2(100),
  PLANETE        VARCHAR2(100),
  TAUX           VARCHAR2(10),
  LOG_ID         NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources composites
CREATE TABLE STG_RAW_COMP_RES (
  NAME             VARCHAR2(100),
  ICON_URL         VARCHAR2(500),
  RESOURCE_1_NAME  VARCHAR2(100),
  RESOURCE_2_NAME  VARCHAR2(100),
  GAZ_NAME         VARCHAR2(100),
  LOG_ID           NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources naturelles (métadonnées)
CREATE TABLE STG_RAW_NAT_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500),
  LOG_ID     NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources naturelles (taux par planète)
CREATE TABLE STG_RAW_NAT_RES_RATE (
  RESOURCE_NAME  VARCHAR2(100),
  PLANETE        VARCHAR2(100),
  TAUX           VARCHAR2(10),
  LOG_ID         NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources raffinées
CREATE TABLE STG_RAW_REF_RES (
  NAME               VARCHAR2(100),
  ICON_URL           VARCHAR2(500),
  RAW_RESOURCE_NAME  VARCHAR2(100),
  LOG_ID             NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);

-- Ressources universelles
CREATE TABLE STG_RAW_UNI_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500),
  LOG_ID     NUMBER REFERENCES STG_RAW_LOG(ID_LOG)
);