CREATE USER TALEND IDENTIFIED BY "Passw0rd#2025"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

  
BEGIN
  ORDS.ENABLE_SCHEMA(
    p_enabled => TRUE,
    p_schema => 'TALEND',
    p_url_mapping_pattern => 'talend',
    p_auto_rest_auth => FALSE
  );
  COMMIT;
END;
/

ALTER USER TALEND ACCOUNT UNLOCK;

GRANT CREATE SESSION TO TALEND;
GRANT CONNECT TO TALEND;
GRANT RESOURCE TO TALEND;

GRANT SELECT ON STG_RAW.COMP_RES       TO TALEND;
GRANT SELECT ON STG_RAW.NAT_RES        TO TALEND;
GRANT SELECT ON STG_RAW.NAT_RES_RATE   TO TALEND;
GRANT SELECT ON STG_RAW.REF_RES        TO TALEND;
GRANT SELECT ON STG_RAW.UNI_RES        TO TALEND;
GRANT SELECT ON STG_RAW.PLANET         TO TALEND;
GRANT SELECT ON STG_RAW.ATMO_RES_RATE  TO TALEND;
GRANT SELECT ON STG_RAW.ATMO_RES       TO TALEND;
GRANT SELECT ON STG_RAW.LOG            TO TALEND;
