-- Table des logs
CREATE TABLE STG_RAW.LOG (
  LOG_ID     NUMBER PRIMARY KEY,
  TABLE_NAME VARCHAR2(100),
  LOG_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


-- Ressources atmosphériques (métadonnées)
CREATE TABLE STG_RAW.ATMO_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500),
  LOG_ID     NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);

-- Ressources atmosphériques (taux par planète)
CREATE TABLE STG_RAW.ATMO_RES_RATE (
  RESOURCE_NAME  VARCHAR2(100),
  PLANETE        VARCHAR2(100),
  TAUX           VARCHAR2(10),
  LOG_ID         NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);

-- Ressources composites
CREATE TABLE STG_RAW.COMP_RES (
  NAME             VARCHAR2(100),
  ICON_URL         VARCHAR2(500),
  RESOURCE_1_NAME  VARCHAR2(100),
  RESOURCE_2_NAME  VARCHAR2(100),
  GAZ_NAME         VARCHAR2(100),
  LOG_ID           NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);

-- Ressources naturelles (métadonnées)
CREATE TABLE STG_RAW.NAT_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500),
  LOG_ID     NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);

-- Ressources naturelles (taux par planète)
CREATE TABLE STG_RAW.NAT_RES_RATE (
  RESOURCE_NAME  VARCHAR2(100),
  PLANETE        VARCHAR2(100),
  TAUX           VARCHAR2(10),
  LOG_ID         NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);

-- Ressources raffinées
CREATE TABLE STG_RAW.REF_RES (
  NAME               VARCHAR2(100),
  ICON_URL           VARCHAR2(500),
  NAT_RESOURCE_NAME  VARCHAR2(100),
  LOG_ID             NUMBER REFERENCES STG_RAW.LOG(LOG_ID)
);


-- Ressources spéciales (métadonnées)
CREATE TABLE STG_RAW.SPE_RES (
  NAME       VARCHAR2(100),
  ICON_URL   VARCHAR2(500)
);

ALTER TABLE STG_RAW.SPE_RES
ADD CONSTRAINT SPE_RES_PK PRIMARY KEY (NAME) ENABLE;

-- Vue "toutes ressources"
CREATE VIEW STG_RAW.V_ALL_RES AS
SELECT NAME, ICON_URL FROM STG_RAW.ATMO_RES
UNION ALL
SELECT NAME, ICON_URL FROM STG_RAW.COMP_RES
UNION ALL
SELECT NAME, ICON_URL FROM STG_RAW.NAT_RES
UNION ALL
SELECT NAME, ICON_URL FROM STG_RAW.REF_RES
UNION ALL
SELECT NAME, ICON_URL FROM STG_RAW.SPE_RES

