CREATE TABLE ODS.ODS_LOG (
  LOG_ID        NUMBER NOT NULL,
  PIPELINE      VARCHAR2(100),
  START_TS      TIMESTAMP,
  END_TS        TIMESTAMP,
  STATUS        VARCHAR2(20),
  ROWS_READ     NUMBER,
  ROWS_WRITTEN  NUMBER,
  ERROR_MSG     VARCHAR2(4000),

  CONSTRAINT PK_ODS_LOG PRIMARY KEY (LOG_ID)
);

CREATE SEQUENCE ODS.LOG_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;


CREATE SEQUENCE ODS.RESOURCES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.RESOURCES (
  RESOURCE_ID    NUMBER DEFAULT ODS.RESOURCES_SEQ.NEXTVAL NOT NULL,
  RESOURCE_NAME  VARCHAR2(100) NOT NULL,
  NAME_NORM      VARCHAR2(100) NOT NULL,
  ICON           VARCHAR2(255),
  RESOURCE_TYPE  VARCHAR2(50) NOT NULL,
  LOG_ID         NUMBER,

  CREATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_RESOURCES PRIMARY KEY (RESOURCE_ID),
  CONSTRAINT UQ_RESOURCES_RESOURCE_NAME UNIQUE (RESOURCE_NAME),
  CONSTRAINT UQ_RESOURCES_NAME_NORM UNIQUE (NAME_NORM),
  CONSTRAINT FK_LOG_RESOURCE FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);


CREATE SEQUENCE ODS.PLANET_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.PLANET (
  PLANET_ID             NUMBER DEFAULT ODS.PLANET_SEQ.NEXTVAL NOT NULL,
  PLANET_NAME           VARCHAR2(100) NOT NULL,
  NAME_NORM             VARCHAR2(100) NOT NULL,

  PRIMARY_RESOURCE_ID   NUMBER,
  SECONDARY_RESOURCE_ID NUMBER,

  DIFFICULTY            VARCHAR2(50),
  SOLAR_POWER           VARCHAR2(50),
  WIND_POWER            VARCHAR2(50),
  CORE_SYMBOL           VARCHAR2(500),
  CORE_MATERIAL         VARCHAR2(100),

  LOG_ID                NUMBER,

  CREATE_TS             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_PLANET PRIMARY KEY (PLANET_ID),
  CONSTRAINT UQ_PLANET_PLANET_NAME UNIQUE (PLANET_NAME),
  CONSTRAINT UQ_PLANET_NAME_NORM UNIQUE (NAME_NORM),

  CONSTRAINT FK_PLANET_PRIMARY_RESOURCE FOREIGN KEY (PRIMARY_RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID),

  CONSTRAINT FK_PLANET_SECONDARY_RESOURCE FOREIGN KEY (SECONDARY_RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID),

  CONSTRAINT FK_LOG_PLANET FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);


CREATE TABLE ODS.PLANET_ATMOSPHERIC_RESOURCE (
  PLANET_ID     NUMBER NOT NULL,
  RESOURCE_ID   NUMBER NOT NULL,
  CONCENTRATION NUMBER(10,4),

  LOG_ID        NUMBER,

  CREATE_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_RESOURCE_ATMOSPHERIC PRIMARY KEY (RESOURCE_ID, PLANET_ID),

  CONSTRAINT FK_ATMO_RESOURCE FOREIGN KEY (RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID),

  CONSTRAINT FK_ATMO_PLANET FOREIGN KEY (PLANET_ID)
    REFERENCES ODS.PLANET(PLANET_ID),

  CONSTRAINT FK_LOG_ATMO FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);


CREATE TABLE ODS.RESOURCE_REFINED (
  REFINED_RESOURCE_ID NUMBER NOT NULL,
  SOURCE_RESOURCE_ID  NUMBER NOT NULL,
  PROCESS_DESCRIPTION VARCHAR2(255),

  CREATE_TS           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_RESOURCE_REFINED PRIMARY KEY (REFINED_RESOURCE_ID, SOURCE_RESOURCE_ID),

  CONSTRAINT FK_REFINED_RESOURCE FOREIGN KEY (REFINED_RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID),

  CONSTRAINT FK_SOURCE_RESOURCE FOREIGN KEY (SOURCE_RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID)
);


CREATE TABLE ODS.PLANET_NATURAL_RESOURCE (
  PLANET_ID      NUMBER NOT NULL,
  RESOURCE_ID    NUMBER NOT NULL,
  AVAILABLE_FLAG NUMBER(1) NOT NULL,

  CREATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_PLANET_RESOURCE PRIMARY KEY (PLANET_ID, RESOURCE_ID),

  CONSTRAINT FK_PR_PLANET FOREIGN KEY (PLANET_ID)
    REFERENCES ODS.PLANET(PLANET_ID),

  CONSTRAINT FK_PR_RESOURCE FOREIGN KEY (RESOURCE_ID)
    REFERENCES ODS.RESOURCES(RESOURCE_ID)
);


