CREATE SEQUENCE ODS.ITEM_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE TABLE ODS.ITEM (
  ITEM_ID    NUMBER DEFAULT ODS.ITEM_SEQ.NEXTVAL NOT NULL,
  ITEM_NAME  VARCHAR2(100) NOT NULL,
  TITLE     VARCHAR2(100) NOT NULL,
  NAME_NORM  VARCHAR2(100) NOT NULL,
  URL            VARCHAR2(500), 
  IMG_SRC_URL   VARCHAR2(255),
  ICON_SRC_URL   VARCHAR2(255),
  ITEM_TIER  VARCHAR2(50) ,
  ITEM_GROUP  VARCHAR2(50) ,
  ITEM_TYPE  VARCHAR2(50),
  DESIGN    VARCHAR2(255),
  CRAFTED_AT    VARCHAR2(50),
  UNLOCK_COST    VARCHAR2(50),
  LOG_ID     NUMBER,
  CREATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID),
  CONSTRAINT UQ_ITEM_ITEM_NAME UNIQUE (ITEM_NAME),
  CONSTRAINT UQ_ITEM_NAME_NORM UNIQUE (NAME_NORM),
  CONSTRAINT FK_LOG_ITEM FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID)
);


CREATE TABLE ODS.ITEM_DESIGN
(
  ITEM_ID        NUMBER NOT NULL,
  RESOURCE_ID    NUMBER NOT NULL,
  QUANTITY       NUMBER NOT NULL,
  LOG_ID         NUMBER,
  CREATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ITEM_DESIGN PRIMARY KEY (ITEM_ID, RESOURCE_ID),
  CONSTRAINT FK_LOG_DESIGN FOREIGN KEY (LOG_ID)
    REFERENCES ODS.ODS_LOG(LOG_ID),
  CONSTRAINT FK_DESIGN_ITEM FOREIGN KEY (ITEM_ID)
    REFERENCES ODS.ITEM(ITEM_ID),
  CONSTRAINT FK_DESIGN_RESOURCE FOREIGN KEY (RESOURCE_ID)
    REFERENCES ODS.RESOURCE(RESOURCE_ID)
)
;